import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { execFileSync } from 'node:child_process';

const root=process.cwd(), runId='skill05-initial-content-package-2026-08-07-refashion-lab';
const prep=path.join(root,'content-prep/prepared-content');
const build=path.join(root,'content-prep/package-build');
const packages=path.join(root,'content-prep/packages');
const planning=path.join(root,'docs/planning');
const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex').toUpperCase();
const ensure=p=>fs.mkdirSync(p,{recursive:true});
const write=(p,v)=>{ensure(path.dirname(p));fs.writeFileSync(p,v)};
const walk=d=>fs.existsSync(d)?fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(d,e.name)):[path.join(d,e.name)]):[];
if(fs.existsSync(build)) throw new Error('PACKAGE_BUILD_ALREADY_EXISTS');
ensure(build); ensure(packages);
const jsonFiles=walk(path.join(prep,'articles')).filter(p=>p.endsWith('.json')).sort();
if(jsonFiles.length!==50) throw new Error(`PREPARED_COUNT_${jsonFiles.length}`);
const rows=jsonFiles.map(p=>JSON.parse(fs.readFileSync(p,'utf8')));
const media=JSON.parse(fs.readFileSync(path.join(prep,'media-manifest.json'),'utf8'));
const categoryMap={}; const approved=[];
for(const row of rows){
  categoryMap[row.category_slug] ||= {section_slug:row.section_slug,post_slugs:[]};
  categoryMap[row.category_slug].post_slugs.push(row.slug); approved.push({slug:row.slug,category_slug:row.category_slug,section_slug:row.section_slug});
  const frontmatter=JSON.stringify(row,null,2);
  const body=row.body.replaceAll(`(/assets/images/${row.slug}/featured.png)`,`(/assets/images/${row.slug}/featured.png)`).replaceAll(`(/assets/images/${row.slug}/closing.png)`,`(/assets/images/${row.slug}/closing.png)`);
  write(path.join(build,'articles',row.category_slug,row.slug,'article.md'),`---\n${frontmatter}\n---\n\n${body.trim()}\n`);
}
for(const item of media.items){const source=path.join(prep,item.target_path.replace('/assets/images/','assets/images/')); const target=path.join(build,item.target_path.replace(/^\//,'')); if(!fs.existsSync(source)) throw new Error(`MEDIA_SOURCE_MISSING_${item.target_path}`); ensure(path.dirname(target)); fs.copyFileSync(source,target);}
write(path.join(build,'approved-slugs.json'),JSON.stringify({schema_version:'v1',run_id:runId,slugs:approved},null,2)+'\n');
write(path.join(build,'category-map.json'),JSON.stringify({schema_version:'v1',run_id:runId,categories:categoryMap},null,2)+'\n');
write(path.join(build,'media-manifest.json'),JSON.stringify({...media,run_id:runId},null,2)+'\n');
const identity='AF077257CD24F4C1FE42BACEA97A29636F46B1D2B0F3DED2CC83E19D1E4FDB46';
const outZip=path.join(packages,`refashion-lab-content-package-${runId}.zip`);
const evidence=path.join(packages,`package-toolkit-evidence-${runId}.json`);
const toolkit='D:\\SiteFactory\\sites-factory-skills\\05\\tools\\package-toolkit\\bin\\package-toolkit.mjs';
execFileSync('node',[toolkit,'build','--source',build,'--output',outZip,'--site-id','refashion-lab','--run-id',runId,'--evidence',evidence],{stdio:'inherit'});
const toolkitEvidence=JSON.parse(fs.readFileSync(evidence,'utf8'));
const packageManifestSource=path.join(build,'package-manifest-v1.json');
const temp=path.join(packages,`reopen-${runId}`); ensure(temp);
execFileSync('tar',['-xf',outZip,'-C',temp],{stdio:'ignore'});
const zipFiles=walk(temp).map(p=>{const rel=path.relative(temp,p).replaceAll('\\','/'); return {relative_path:rel,size_bytes:fs.statSync(p).size,sha256:sha(p),file_role:rel.endsWith('/article.md')?'article':rel.includes('assets/images/')?'media':path.basename(p)==='approved-slugs.json'?'approved-slugs':path.basename(p)==='category-map.json'?'category-map':path.basename(p)==='media-manifest.json'?'media-manifest':'package-manifest'};});
const normalized=JSON.stringify(zipFiles.sort((a,b)=>a.relative_path.localeCompare(b.relative_path)),null,2)+'\n';
const fileManifestPath=path.join(packages,`package-file-manifest-${runId}.json`); write(fileManifestPath,normalized);
const outer=sha(outZip), fileManifestSha=sha(fileManifestPath), total=zipFiles.reduce((n,x)=>n+x.size_bytes,0);
const packageManifest={schema_version:'v1',package_type:'initial-content-package',site_id:'refashion-lab',run_id:runId,target_site_id:'refashion-lab',target_project_identity_sha256:identity,project_contract_version:'skill03-local-build-exception-v1',media_contract_version:'v2',media_root:'/assets/images/',article_count:50,category_count:Object.keys(categoryMap).length,section_count:3,legal_pages_verified_for_frontend:true,legal_pages_in_admin_upload_zip:false,missing_media_assignment:0,content_fingerprint:toolkitEvidence.content_fingerprint,outer_archive_sha256:outer,normalized_file_manifest_sha256:fileManifestSha};
write(path.join(packages,`package-manifest-${runId}.json`),JSON.stringify(packageManifest,null,2)+'\n');
write(path.join(packages,`approved-slugs-${runId}.json`),JSON.stringify({schema_version:'v1',run_id:runId,slugs:approved},null,2)+'\n');
write(path.join(packages,`category-map-${runId}.json`),JSON.stringify({schema_version:'v1',run_id:runId,categories:categoryMap},null,2)+'\n');
write(path.join(packages,`media-manifest-${runId}.json`),JSON.stringify({...media,run_id:runId},null,2)+'\n');
const articlePaths=zipFiles.filter(x=>x.file_role==='article').map(x=>x.relative_path);
if(articlePaths.length!==50 || articlePaths.some(p=>!/^articles\/[^/]+\/[^/]+\/article\.md$/.test(p))) throw new Error('ARTICLE_PATH_VALIDATION_FAILED');
const forbidden=zipFiles.filter(x=>/^(legal-pages|docs|imports|content-prep|prepared-content|raw source)\//.test(x.relative_path));
if(forbidden.length) throw new Error('FORBIDDEN_PACKAGE_ROOT');
const reportPath=path.join(root,'content-prep',`package-report-${runId}.md`);
write(reportPath,`# Skill 05 Package Report\n\n- run_id: ${runId}\n- package type: initial-content-package\n- article count: 50\n- category count: ${Object.keys(categoryMap).length}\n- media items: ${media.items.length}\n- legal pages verified for frontend: 4\n- legal markdown in Admin ZIP: 0\n- allowed roots: articles, assets, approved-slugs.json, category-map.json, media-manifest.json, package-manifest-v1.json\n- outer SHA256: ${outer}\n- normalized file count: ${zipFiles.length}\n- normalized file manifest SHA256: ${fileManifestSha}\n- total uncompressed bytes: ${total}\n- toolkit reopen verification: PASS\n- Admin upload / Preview / Apply: NOT RUN\n- final status: PASS_PACKAGE_READY_FOR_ADMIN_IMPORT\n`);
const cleanupPath=path.join(planning,`skill05-cleanup-report-${runId}.json`); write(cleanupPath,JSON.stringify({schema_version:'v1',run_id:runId,inventory_count:zipFiles.length,cleanup_preview_count:1,exact_path_actions:[{path:path.relative(root,build).replaceAll('\\','/'),action:'RETAIN_TEMPORARY_UNTIL_SKILL06_HANDOFF',status:'PENDING'}],safe_deleted_file_count:0,review_required_count:0,status:'PASS_NO_DESTRUCTIVE_CLEANUP'},null,2)+'\n');
const artifactPaths=[outZip,fileManifestPath,path.join(packages,`package-manifest-${runId}.json`),path.join(packages,`approved-slugs-${runId}.json`),path.join(packages,`category-map-${runId}.json`),path.join(packages,`media-manifest-${runId}.json`),reportPath,cleanupPath];
const outputEvidence=artifactPaths.map(p=>({path:path.relative(root,p).replaceAll('\\','/'),exists:fs.existsSync(p),non_empty:fs.statSync(p).size>0,sha256:sha(p),size_bytes:fs.statSync(p).size,status:'CURRENT',run_id:runId}));
const manifest={schema_version:'v1',skill_id:'05',site_id:'refashion-lab',run_id:runId,execution_mode:'initial_content_package',preflight:{skill04_handoff_pass:true,prepared_content_found:true,output_manifest_found:true,content_time_policy_found:true,legal_manifest_found:true},package_schema:{allowed_roots_valid:true,article_paths_valid:true,markdown_count:50,article_count:50,forbidden_root_count:0},content_validation:{sections:3,categories:10,articles:50,slugs_unique:true,body_schema:'markdown',seo_geo_preserved:true,time_fields_preserved:true,legal_pages_verified:4},media_validation:{media_contract_version:'v2',media_root:'/assets/images/',featured_count:50,closing_count:50,inline_count:0,missing_media_assignment:0,manifest_matches_files:true,image_uniqueness_blocking_count:0},package_fingerprint:{zip_path:path.relative(root,outZip).replaceAll('\\','/'),outer_archive_sha256:outer,normalized_file_count:zipFiles.length,normalized_file_manifest_path:path.relative(root,fileManifestPath).replaceAll('\\','/'),normalized_file_manifest_sha256:fileManifestSha,total_uncompressed_bytes:total},outputs:outputEvidence,stage_handoff_gate:{artifact_persisted:true,codex_local_validation:'PASS',downstream_handoff_allowed:true},artifact_storage_report:{created_file_count:artifactPaths.length,created_bytes:artifactPaths.reduce((n,p)=>n+fs.statSync(p).size,0),retained_file_count:artifactPaths.length,retained_bytes:artifactPaths.reduce((n,p)=>n+fs.statSync(p).size,0),safe_deleted_file_count:0,safe_deleted_bytes:0,review_required_count:0,inventory_count:zipFiles.length,cleanup_preview_count:1,archived_count:0,deleted_count:0,skipped_count:1,manual_review_count:0,mixed_directory_finding_count:0},final_status:'PASS_PACKAGE_READY_FOR_ADMIN_IMPORT',operating_contract:{site_data_engineering:true,build_required:true,admin_package_required:true,unique_current_package:true},lifecycle_contract_version:'v1',lifecycle_registry_path:'docs/planning/artifact-lifecycle-registry-v1.json',cleanup_report_path:path.relative(root,cleanupPath).replaceAll('\\','/'),output_path_contract_version:'site-factory-output-path-contract-v1',output_path_evidence:{contract_version:'site-factory-output-path-contract-v1',project_root:root,run_id:runId,paths:outputEvidence},media_role_contract:{contract_version:'site-factory-media-role-contract-v1',item_count:100,featured_count:50,closing_count:50,inline_count:0,missing_media_assignment:0,manifest_path:path.relative(root,path.join(packages,`media-manifest-${runId}.json`)).replaceAll('\\','/'),manifest_sha256:sha(path.join(packages,`media-manifest-${runId}.json`)),media_contract_version:'v2',media_root:'/assets/images/',validator_contract_version:'site-factory-validator-media-path-contract-v1'},validator_media_path_validation:{contract_version:'site-factory-validator-media-path-contract-v1',status:'PASS',missing_media_assignment:0,absolute_path_count:0},project_identity_evidence:{site_id:'refashion-lab',project_identity_sha256:identity,project_contract_version:'skill03-local-build-exception-v1',identity_status:'PASS',package_target_identity_match:true,preview_apply_identity_match:false,release_identity_match:false},editorial_content_quality:{quality_status:'PASS',total_hits:0},semantic_quality_report_path:null,composite_content_quality_status:'COMPOSITE_CONTENT_QUALITY_PASS',orchestration:{orchestrator:'skill05',orchestrator_version:'149-v1',mode:'build_package',status:'PASS',stage_id:'05_initial_content_package',next_stage:'06_initial_admin_import',resume_token:runId,input_identity:{skill04_run_id:'skill04-initial-content-preparation-2026-08-07-refashion-lab'},output_identity:{zip_outer_sha256:outer},human_approval_refs:[],skip_decisions:[{stage:'admin_upload',decision:'not_run',reason:'Skill 05 boundary'}]}};
write(path.join(planning,`05-skill-output-manifest-${runId}.json`),JSON.stringify(manifest,null,2)+'\n');
write(path.join(planning,`orchestrator-handoff-05-${runId}.json`),JSON.stringify({schema_version:'v1',run_id:runId,stage_id:'05_initial_content_package',status:'PASS',next_stage:'06_initial_admin_import',artifact_persisted:true,codex_local_validation:'PASS',downstream_handoff_allowed:true,package_path:path.relative(root,outZip).replaceAll('\\','/'),outer_archive_sha256:outer},null,2)+'\n');
console.log(JSON.stringify({run_id:runId,zip:path.relative(root,outZip),outer_sha256:outer,normalized_file_count:zipFiles.length,status:'PASS_PACKAGE_READY_FOR_ADMIN_IMPORT'},null,2));
